name: Validate and Plan Terraform - Development
on:
  push:
    branches: [development]

jobs:
  validate-and-plan-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Terraform init
        run: cd terraform && terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        run: cd terraform && terraform plan -input=false -no-color -out plan.tf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Pull-request:
    runs-on: ubuntu-latest
    needs: [validate-and-plan-terraform]
    steps:
      - uses: actions/checkout@v2
      
      - name: Create pull request
        run: gh pr create -B main -H development --title 'Merge development into main' --body 'Created by Github action' || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

